name: Lint

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
          - name: copy reposit
            uses: actions/checkout@v3

          - name: install Py
            uses: actions/setup-python@v4
            with:
                python-version: '3.12'

          - name: install linters
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
          - name: run ruff
            run: ruff check .

          - name: run black
            run: black --check .

          - name: run mypy
            run: mypy .
          

          - name: run tests
            run: pytest
