name: Lint

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
          - name: copy reposit
            uses: actions/checkout@v3

          - name: install Py
            uses: actions/setup-python@v4
            with:
                python-version: '3.12'

          - name: install linters
            run: |
                python -m pip install --upgrade pip
                pip install bandit
                pip install -r requirements.txt
                
          - name: run ruff
            run: ruff check .

          - name: run black
            run: black --check .

          - name: run mypy
            run: mypy .
          
          - name: run bandit
            run: bandit -r . -x ./venv/ -x ./tests/

          - name: run tests
            run: pytest

    gitleaks:
        runs-on: ubuntu-latest

        steps:
          - name: copy reposit
            uses: actions/checkout@v3
            with: 
              fetch-depth: 0

          - name: run gitleaks
            uses: zricethezav/gitleaks-action@v1.5.0
            with:
              config-path: .gitleaks.toml
    
    trivy:
        runs-on: ubuntu-latest

        steps:
          - name: copy reposit
            uses: actions/checkout@v3 

          - name: run trivy
            uses: aquasecurity/trivy-action@master
            with:
              scan-type: "fs"
              input: "requirements.txt"

